apiVersion: v1
kind: ConfigMap
metadata:
  name: pensum-backend-config
  namespace: pensum-cloud
data:
  NODE_ENV: "production"
  JWT_EXPIRATION: "15m"
  JWT_REFRESH_EXPIRATION: "7d"
  PORT: "3000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pensum-frontend-config
  namespace: pensum-cloud
data:
  NGINX_PORT: "80"
