apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: pensum-cloud
  labels:
    app: postgres
spec:
  type: ClusterIP       # internal only — backend accesses via DNS: postgres:5432
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
