apiVersion: v1
kind: Service
metadata:
  name: pensum-frontend
  namespace: pensum-cloud
  labels:
    app: pensum-frontend
spec:
  type: ClusterIP
  selector:
    app: pensum-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
